In [35]:
emp=open("C:/Users/Localadmin/Downloads/emp12.csv","r")

In [36]:
for i in f:
    print(i)

In [37]:
for x in emp:
    row=x.split(",")
    salary=int(row[5])
    print("total salary for" +" "+ row[1] +" "+ "is"+" " + str(salary))
    DA=salary*0.25
    print("DA is"+str(DA))
    TZ=salary*0.15
    print("TZ is"+str(TZ))
    HRA=salary*0.16
    print("HRA is"+str(HRA))
    CCA=salary*0.02
    print("CCA is"+str(CCA))
    MA=salary*0.05
    print("MA is"+str(MA))
    LIC=salary*0.5
    print("LIC is"+str(LIC))
    Netsalary=DA+TZ+HRA+MA+LIC
    print("Net-sal for"+ " " +row[1]+" " +"is"+ " " + str(Netsalary))
print("\n")

total salary for Sheethal is 25000
DA is6250.0
TZ is3750.0
HRA is4000.0
CCA is500.0
MA is1250.0
LIC is12500.0
Net-sal for Sheethal is 27750.0
total salary for Sonu is 28000
DA is7000.0
TZ is4200.0
HRA is4480.0
CCA is560.0
MA is1400.0
LIC is14000.0
Net-sal for Sonu is 31080.0
total salary for Sandeep is 100000
DA is25000.0
TZ is15000.0
HRA is16000.0
CCA is2000.0
MA is5000.0
LIC is50000.0
Net-sal for Sandeep is 111000.0
total salary for Manoj is 65000
DA is16250.0
TZ is9750.0
HRA is10400.0
CCA is1300.0
MA is3250.0
LIC is32500.0
Net-sal for Manoj is 72150.0
total salary for Prasanna is 15000
DA is3750.0
TZ is2250.0
HRA is2400.0
CCA is300.0
MA is750.0
LIC is7500.0
Net-sal for Prasanna is 16650.0
total salary for Priyanka is 20000
DA is5000.0
TZ is3000.0
HRA is3200.0
CCA is400.0
MA is1000.0
LIC is10000.0
Net-sal for Priyanka is 22200.0
total salary for Shravanthi is 28000
DA is7000.0
TZ is4200.0
HRA is4480.0
CCA is560.0
MA is1400.0
LIC is14000.0
Net-sal for Shravanthi is 31080.0
total salary for Yamini is 19000
DA is4750.0
TZ is2850.0
HRA is3040.0
CCA is380.0
MA is950.0
LIC is9500.0
Net-sal for Yamini is 21090.0
total salary for Chaitanya is 25000
DA is6250.0
TZ is3750.0
HRA is4000.0
CCA is500.0
MA is1250.0
LIC is12500.0
Net-sal for Chaitanya is 27750.0
total salary for Leela Krishna is 26000
DA is6500.0
TZ is3900.0
HRA is4160.0
CCA is520.0
MA is1300.0
LIC is13000.0
Net-sal for Leela Krishna is 28860.0
total salary for Mahender is 60000
DA is15000.0
TZ is9000.0
HRA is9600.0
CCA is1200.0
MA is3000.0
LIC is30000.0
Net-sal for Mahender is 66600.0
total salary for Yelishetty Shankar is 100000
DA is25000.0
TZ is15000.0
HRA is16000.0
CCA is2000.0
MA is5000.0
LIC is50000.0
Net-sal for Yelishetty Shankar is 111000.0
total salary for Swapna is 23000
DA is5750.0
TZ is3450.0
HRA is3680.0
CCA is460.0
MA is1150.0
LIC is11500.0
Net-sal for Swapna is 25530.0
total salary for Nikhil is 25000
DA is6250.0
TZ is3750.0
HRA is4000.0
CCA is500.0
MA is1250.0
LIC is12500.0
Net-sal for Nikhil is 27750.0
total salary for Sai Kumar is 30000
DA is7500.0
TZ is4500.0
HRA is4800.0
CCA is600.0
MA is1500.0
LIC is15000.0
Net-sal for Sai Kumar is 33300.0